version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "echo", "healthcheck"]  # Заглушка для healthcheck
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-container
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started  # FastAPI начнет запуск, когда PostgreSQL будет запущен
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
