apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-model-trained
          image: minure/ml-model-api:latest
          volumeMounts:
            - mountPath: /app/models
              name: model-storage
          command:
          - /bin/sh
          - -c
          - |
            until [ -f /app/models/model.pkl ]; do
            echo 'Waiting for model.pkl to be available...';
            sleep 5;
            done;
      containers:
        - name: api
          image: minure/ml-model-api:latest
          workingDir: /app
          volumeMounts:
            - mountPath: /app/models
              name: model-storage
          env:
            - name: MODEL_PATH
              value: /app/models/model.pkl
          command:
          - python
          - app.py
      restartPolicy: Always
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5252
      targetPort: 5252
      nodePort: 30000
  type: NodePort