apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-postgres-configmap
  labels:
    app: mlflow-postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  MLFLOW_BACKEND_STORE_URI: "postgresql+psycopg2://postgres:postgres@mlflow-postgres:5432/mlflow"